### ISSUE TITLE
PHP8.4 deprecation - Implicitly marking parameter <x> as nullable is deprecated, the explicit nullable type must be used instead

### ISSUE THREAD

**Issue by 3kbest** [matasarei/json-rpc#19]
https://github.com/matasarei/json-rpc/blob/f76b5e9c1a5d987e757d394fbe32d3d9c86f5184/src/JsonRPC/Exception/ResponseException.php#L29

https://github.com/matasarei/json-rpc/blob/f76b5e9c1a5d987e757d394fbe32d3d9c86f5184/src/JsonRPC/Client.php#L58

**Comment by matasarei** [comment]
https://github.com/matasarei/json-rpc/pull/20
